Repository dotnet/BenchmarkDotNet, pull requests merged in 2020-03, with the labels that each got.

#1375 don't require the JitDiagnosers (TailCall & Inlining) to run benchmarks once again just to gather JIT info, the overhead is very small
  src/BenchmarkDotNet.Diagnostics.Windows/JitDiagnoser.cs
Labels: Area:Diagnosers

#1389 Ref readonly support
  src/BenchmarkDotNet/Code/CodeGenerator.cs
  src/BenchmarkDotNet/Code/DeclarationsProvider.cs
  src/BenchmarkDotNet/Engines/DeadCodeEliminationHelper.cs
  src/BenchmarkDotNet/Extensions/ReflectionExtensions.cs
  src/BenchmarkDotNet/Templates/BenchmarkType.txt
  src/BenchmarkDotNet/Templates/CsProj.txt
  src/BenchmarkDotNet/Toolchains/Roslyn/Builder.cs
  tests/BenchmarkDotNet.IntegrationTests/ArgumentsTests.cs
  tests/BenchmarkDotNet.IntegrationTests/ValuesReturnedByBenchmarkTest.cs
  tests/BenchmarkDotNet.Tests/ReflectionTests.cs
Labels: Area:Engine, bug

#1397 Bump macOS Azure Pipeline vmImage to 10.14, fix #1396
  azure-pipelines.macOS.yml
Labels: Area:DevOps
