Repository dotnet/BenchmarkDotNet, pull requests merged in 2020-10, with the labels that each got.

#1552 Enable supported GcMode characteristics with corerun
  src/BenchmarkDotNet/Extensions/ProcessExtensions.cs
Labels: Area:Toolchains

#1547 hardware counters: don't try to exclude non-existing overhead for long running benchmarks
  src/BenchmarkDotNet.Diagnostics.Windows/Tracing/TraceLogParser.cs
Labels: Area:Diagnosers

#1548 Remove the old PmcDiagnoser, EtwProfiler is much more accurate
  src/BenchmarkDotNet.Diagnostics.Windows/PmcDiagnoser.cs
  src/BenchmarkDotNet/Diagnosers/DiagnosersLoader.cs
Labels: Area:Diagnosers, enhancement

#1550 Bring instruction pointer exporter back to live
  src/BenchmarkDotNet.Diagnostics.Windows/EtwProfiler.cs
  src/BenchmarkDotNet.Diagnostics.Windows/Tracing/TraceLogParser.cs
  src/BenchmarkDotNet/Exporters/InstructionPointerExporter.cs
Labels: Area:Diagnosers, Area:Exporters

#1545 Fix Merge operation failed for EtwProfiler
  src/BenchmarkDotNet.Diagnostics.Windows/BenchmarkDotNet.Diagnostics.Windows.csproj
  src/BenchmarkDotNet/BenchmarkDotNet.csproj
  src/BenchmarkDotNet/Helpers/ArtifactFileNameHelper.cs
  tests/BenchmarkDotNet.Tests/ArtifactFileNameHelperTests.cs
Labels: Area:Diagnosers

#1560 Add support for Platform-specific TFMs introduced in .NET 5
  src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
  src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
  src/BenchmarkDotNet/Toolchains/CsProj/CsProjCoreToolchain.cs
  src/BenchmarkDotNet/Toolchains/CsProj/CsProjGenerator.cs
  src/BenchmarkDotNet/Toolchains/ToolchainExtensions.cs
  tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
  tests/BenchmarkDotNet.Tests/Running/JobRuntimePropertiesComparerTests.cs
  tests/BenchmarkDotNet.Tests/RuntimeVersionDetectionTests.cs
Labels: Area:Toolchains, enhancement

#1563 ensure that the auto-generated project alwas has tfm in the output path
  src/BenchmarkDotNet/Templates/CsProj.txt
Labels: Area:Toolchains

#1567 Dont remove artifacts when build fails
  docs/articles/guides/troubleshooting.md
  src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
Labels: Area:Documentation, Area:Toolchains, enhancement

#1571 Dispose parameters, kill benchmarking process when it hangs after printing the results
  src/BenchmarkDotNet/Helpers/ConsoleExitHandler.cs
  src/BenchmarkDotNet/Loggers/SynchronousProcessOutputLoggerWithDiagnoser.cs
  src/BenchmarkDotNet/Parameters/ParameterInstance.cs
  src/BenchmarkDotNet/Parameters/ParameterInstances.cs
  src/BenchmarkDotNet/Parameters/SmartParamBuilder.cs
  src/BenchmarkDotNet/Running/BenchmarkCase.cs
  src/BenchmarkDotNet/Running/BenchmarkRunInfo.cs
  src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs
  src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs
  src/BenchmarkDotNet/Toolchains/Executor.cs
  tests/BenchmarkDotNet.IntegrationTests/ArgumentsTests.cs
Labels: Area:Engine, enhancement

#1573 Don't run the benchmark once per iteration if only the first ivocation lasts longer than IterationTime
  src/BenchmarkDotNet/Engines/EngineFactory.cs
  src/BenchmarkDotNet/Engines/EngineResolver.cs
  tests/BenchmarkDotNet.Tests/Engine/EngineFactoryTests.cs
Labels: Area:Engine

#1580 use Environment.Version to determine .NET 5+ versions
  src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
Labels: Area:Toolchains
