Repository dotnet/BenchmarkDotNet, pull requests merged in 2022-08, with the labels that each got.

#2067 fix .NET 4.8.1 detection
  src/BenchmarkDotNet/Helpers/FrameworkVersionHelper.cs
  tests/BenchmarkDotNet.Tests/FrameworkVersionHelperTests.cs
Labels: Area:Toolchains

#2068 print error when users try DisassemblyDiagnoser with NativeAOT
  src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoser.cs
  src/BenchmarkDotNet/Jobs/EnvironmentMode.cs
  src/BenchmarkDotNet/Jobs/JobExtensions.cs
  src/BenchmarkDotNet/Running/BuildPartition.cs
Labels: Area:Diagnosers

#2071 use ClrMd v2 disassembler on Windows whenever possible
  src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoser.cs
  src/BenchmarkDotNet/Disassemblers/LinuxDisassembler.cs
  src/BenchmarkDotNet/Disassemblers/WindowsDisassembler.cs
Labels: Area:Diagnosers

#2072 Add glob filters support to disassembler to allow disassembling specific methods
  src/BenchmarkDotNet.Disassembler.x64/ClrMdV1Disassembler.cs
  src/BenchmarkDotNet.Disassembler.x64/DataContracts.cs
  src/BenchmarkDotNet/Attributes/DisassemblyDiagnoserAttribute.cs
  src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
  src/BenchmarkDotNet/ConsoleArguments/ConfigParser.cs
  src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs
  src/BenchmarkDotNet/Disassemblers/DisassemblyDiagnoserConfig.cs
  src/BenchmarkDotNet/Disassemblers/SameArchitectureDisassembler.cs
  src/BenchmarkDotNet/Disassemblers/WindowsDisassembler.cs
  src/BenchmarkDotNet/Filters/GlobFilter.cs
  tests/BenchmarkDotNet.IntegrationTests/DisassemblyDiagnoserTests.cs
Labels: Area:Diagnosers

#2073 add two fallbacks to CoreRun copying
  src/BenchmarkDotNet/Toolchains/CoreRun/CoreRunToolchain.cs
Labels: Area:Toolchains

#2075 Fix disassembler
  src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs
Labels: Area:Diagnosers

#2078 More disassembler improvements
  src/BenchmarkDotNet/ConsoleArguments/CommandLineOptions.cs
  src/BenchmarkDotNet/Disassemblers/ClrMdV2Disassembler.cs
  tests/BenchmarkDotNet.Tests/ConfigParserTests.cs
Labels: Area:Diagnosers

#2079 fix the CI
  src/BenchmarkDotNet/Toolchains/NativeAot/Generator.cs
  tests/BenchmarkDotNet.IntegrationTests/NativeAotTests.cs
Labels: Area:Toolchains

#1621 Hide columns for multiple runtime
  src/BenchmarkDotNet/Columns/JobCharacteristicColumn.cs
  src/BenchmarkDotNet/Reports/Summary.cs
Labels: Area:Loggers

#2084 Release notes for 0.13.2
  docs/_changelog/header/v0.13.2.md
Labels: Area:Documentation
