Repository dotnet/BenchmarkDotNet, pull requests merged in 2024-12, with the labels that each got.

#2672 Add documentation for VS Profiler
  build/cSpell.json
  docs/articles/features/toc.yml
  docs/articles/features/vsprofiler.md
  docs/articles/samples/IntroVisualStudioProfiler.md
  docs/articles/samples/toc.yml
  docs/images/vs-profiler-demo.png
  samples/BenchmarkDotNet.Samples/BenchmarkDotNet.Samples.csproj
  samples/BenchmarkDotNet.Samples/IntroVisualStudioDiagnoser.cs
Labels: Area:Diagnosers, Area:Documentation

#2423 Fix builds when --keepFiles is specified
  src/BenchmarkDotNet/Running/BuildPartition.cs
  tests/BenchmarkDotNet.IntegrationTests/InProcessEmitTest.cs
Labels: bug

#2674 add HostSignal.AfterProcessStart to allow the users to obtain ID of a process that was started suspended
  src/BenchmarkDotNet/Engines/HostSignal.cs
  src/BenchmarkDotNet/Loggers/Broker.cs
  src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs
  src/BenchmarkDotNet/Toolchains/Executor.cs
Labels: Area:Diagnosers
