Repository dotnet/BenchmarkDotNet, pull requests merged in 2025-06, with the labels that each got.

#2562 Improve memory diagnoser accuracy
  src/BenchmarkDotNet/Engines/Engine.cs
  src/BenchmarkDotNet/Engines/GcStats.cs
  src/BenchmarkDotNet/Portability/RuntimeInformation.cs
  tests/BenchmarkDotNet.IntegrationTests/BenchmarkDotNet.IntegrationTests.csproj
  tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
Labels: Area:Diagnosers

#2775 chore: Modify macos runner image for CI
  .github/workflows/run-tests.yaml
  build/BenchmarkDotNet.Build/Runners/UnitTestRunner.cs
Labels: Area:DevOps

#2790 fix: Console logs are outputted twice when using TestAdapter
  src/BenchmarkDotNet.TestAdapter/BenchmarkExecutor.cs
  src/BenchmarkDotNet/Configs/ManualConfig.cs
Labels: Area:Loggers
