Repository dotnet/BenchmarkDotNet, pull requests merged in 2025-07, with the labels that each got.

#2799 Fix `IsNetCore` and `IsNativeAOT` for single-file apps without AOT
  src/BenchmarkDotNet/Environments/Runtimes/CoreRuntime.cs
  src/BenchmarkDotNet/Portability/RuntimeInformation.cs
Labels: bug

#2813 chore: Fix flaky AllocationQuantumIsNotAnIssueForNetCore21Plus tests on macos
  tests/BenchmarkDotNet.IntegrationTests/MemoryDiagnoserTests.cs
Labels: Area:DevOps

#2814 Use `--nodeReuse:false`
  src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs
Labels: Area:Toolchains
